# Generated by Django 3.0.7 on 2020-07-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_extraimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
